### ISSUE TITLE
Странная рекурсия, но допустим

### ISSUE THREAD

**Issue by AlexPshkov** [qasmark/FLP#1]
https://github.com/qasmark/FLP/blob/d056e0b7de3405bee1689d0e06f80f93203e3f01/lw3/funcs.hs#L10

**Comment by qasmark** [comment]
**Операция головы для присоединения элемента в список через рекурсию**

```Bash
> go 5
5 : go 4
5 : 4 go 3
5 : 4 : 3 : go  2
5 : 4 : 3 : 2 : 1 : go 
5 : 4 : 3 : 2 : 1: []
[5,4,3,2,1]
```
