### ISSUE TITLE
Рекурсии нет вообще

### ISSUE THREAD

**Issue by AlexPshkov** [qasmark/FLP#2]
Нет рекурсии и странная логика работы:
  Тест `[[1], [], [2]]` выдает `Nothing`, хотя логично бы было выдать [1,2]

https://github.com/qasmark/FLP/blob/d056e0b7de3405bee1689d0e06f80f93203e3f01/lw3/funcs.hs#L17

**Comment by qasmark** [comment]
Работает, насяльника
