### ISSUE TITLE
На значении n = -1 просто падает

### ISSUE THREAD

**Issue by AlexPshkov** [qasmark/FLP#3]
Нужна обработка минусового значения для n
https://github.com/qasmark/FLP/blob/d056e0b7de3405bee1689d0e06f80f93203e3f01/lw3/funcs.hs#L61

**Comment by qasmark** [comment]
Работает, насяльника!!


![image](https://github.com/user-attachments/assets/47f07cfd-3ad4-4634-a978-cdb599a9fa72)
