### ISSUE TITLE
Доработка

### ISSUE THREAD

**Issue by AlexPshkov** [qasmark/FLP#4]
Давай тут добавим проверку на ретроградный меркурий
https://github.com/qasmark/FLP/blob/53973af3433655516b40cfa8d57752d3b7a3dc2d/lw3/funcs.hs#L46

**Comment by qasmark** [comment]
![image](https://github.com/user-attachments/assets/faed0c59-9352-41b0-8c72-c15b00215470)

**Извините, в этом году следующий ретроградный меркурий через 2 месяца. Обсудим в следующей итерации**
