### ISSUE TITLE
Не учтено

### ISSUE THREAD

**Issue by AlexPshkov** [qasmark/FLP#5]
Не учтена фаза луны
https://github.com/qasmark/FLP/blob/53973af3433655516b40cfa8d57752d3b7a3dc2d/lw3/funcs.hs#L9

**Comment by qasmark** [comment]
**Возраст луны определяется числом дней, прошедших от фазы новолуния (конъ- юнкция). Например, если новолуние пришлось на 14 июня на 6 часов утра (воз- раст луны = 0), то возраст луны 15 июня в 6 часов вечера составит 1,5 дня (прошло 36 часов).**
